require './test'

TOTAL_GAMES = 10

MIN_INNINGS = 9
MAX_OUTS = 3
MAX_BALLS = 4
MAX_STRIKES = 3

# HOME - SAN FRANCISCO GIANTS
# AWAY - LOS ANGELES DODGERS
# Using - http://www.espn.com/mlb/stats/team/_/stat/batting/year/2017/type/expanded-2

HOM = "SFG"
AWA = "LAD"

# Groundball to Flyball Ratio *10
HOME_HITS_PER_TEN_FLY = 93
AWAY_HITS_PER_TEN_FLY = 79


HOME_FLY_FIELDING_RATING_BASE = 200
AWAY_FLY_FIELDING_RATING_BASE = 200
FLY_FIELDING_RATING_MODIFIER = 100

HOME_GROUND_FIELDING_RATING_BASE = 50
AWAY_GROUND_FIELDING_RATING_BASE = 50
GROUND_FIELDING_RATING_MODIFIER = 25

 # Hits - (Doubles + Triples + Homeruns) per Games
HOME_SINGLE_RATIO = 1382-290-28-128
AWAY_SINGLE_RATIO = 1347-312-20-221

# Doubles per Game
HOME_DOUBLE_RATIO = 290
AWAY_DOUBLE_RATIO = 312

# Triples per Game
HOME_TRIPLE_RATIO = 28
AWAY_TRIPLE_RATIO = 20

# Homeruns per Game
HOME_HOMERUN_RATIO = 128
AWAY_HOMERUN_RATIO = 221

# Opponent's Grounded into Double Plays
HOME_DOUBLE_PLAY_RATING_BASE = 119
AWAY_DOUBLE_PLAY_RATING_BASE = 136
DOUBLE_PLAY_RATING_MODIFIER = 100
DOUBLE_PLAY_NEEDED = 175

# 1000 - Opp Bat Avg (Def Stat)
HOME_PITCHER_RATING_BASE = 1000 - 331
AWAY_PITCHER_RATING_BASE = 1000 - 290
PITCHER_RATING_MODIFIER = 40


HOME_PITCHING_STAMINA = 290
AWAY_PITCHING_STAMINA = 290

# PITCH_MIN must be greater than MAX_BALL_RATING
PITCH_MIN = 25
HOME_BALL_RATIO = 0.5
AWAY_BALL_RATIO = 0.5

# puts ('PITCH_MIN must be greater than MAX_BALL_RATING').red if PITCH_MIN < MAX_BALL_RATING
# exit if PITCH_MIN < MAX_BALL_RATING

# Bat Avg
HOME_BATTER_RATING_BASE = 249
AWAY_BATTER_RATING_BASE = 249
BATTER_RATING_MODIFIER = 25

PITCHER_RATIO = 1.0
FIELDER_RATIO = 2.5
BATTER_RATIO = 1.0

PLAY_MERCY_RULE = false
MERCY_LIMIT = 10
BLOWOUT_LIMIT = 12

INNING_MULTIPLIER = 5

EMPTY_BASE = "\u25C7"
MAN_ON_BASE = "\u25C6"
NOT_OUT = "\u25CB"
IS_OUT = "\u25CF"

test_game
# testing
